CREATE TABLE TransactionTable (
	TRANSACTION_ID INT(8) PRIMARY KEY,
	DATE_CREATED DATE NOT NULL,
	AMOUNT DECIMAL(8,2) NOT NULL,
	TRANSACTION_TYPE VARCHAR(40) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	DESCRIPTION TEXT,
	DATE_MODIFIED DATE
	);

CREATE TABLE Constants (
	NAME VARCHAR(40) NOT NULL,
	DATA_TYPE VARCHAR(40) NOT NULL,
	VALUE VARCHAR(40) NOT NULL
	);