CREATE TABLE Constants (
	NAME VARCHAR(40) NOT NULL,
	DATA_TYPE VARCHAR(40) NOT NULL,
	VALUE VARCHAR(40) NOT NULL
	);

CREATE TABLE TransactionTable (
	TRANSACTION_ID INTEGER(8) PRIMARY KEY,
	DATE_CREATED DATE NOT NULL,
	AMOUNT DECIMAL(8,2) NOT NULL,
	TRANSACTION_TYPE VARCHAR(40) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	DESCRIPTION TEXT,
	DATE_MODIFIED DATE
	);

CREATE TABLE ModificationTable (
	MODIFICATION_ID INTEGER(8) PRIMARY KEY,
	TRANSACTION_ID INTEGER(8),
	ORIGINAL_AMOUNT DECIMAL(8,2),
	ORIGINAL_CATEGORY VARCHAR(50),
	ORIGINAL_DESCRIPTION TEXT,
	NEW_AMOUNT DECIMAL(8,2),
	NEW_CATEGORY VARCHAR(40),
	NEW_DESCRIPTION TEXT,
	CURRENT_DATE DATE NOT NULL,
	PREVIOUS_DATE DATE,
	FOREIGN KEY(TRANSACTION_ID) REFERENCES TransactionTable(TRANSACTION_ID)
	);